services:
  - type: web
    name: vetscope
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        sync: false
      - key: MODEL_PATH
        value: /opt/render/project/src/models/dog_disease_model_96.h5
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/models
      sizeGB: 1 